In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("training_data.csv")

In [3]:
df

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,42.0,Male,46.0,30.0,3.0,4.0,Standard,Annual,945.08,8.0,0.0
1,33.0,Female,43.0,17.0,1.0,15.0,Standard,Annual,987.79,12.0,0.0
2,26.0,Female,13.0,30.0,4.0,12.0,Premium,Quarterly,800.00,5.0,1.0
3,29.0,Female,9.0,23.0,10.0,24.0,Basic,Quarterly,119.00,19.0,1.0
4,38.0,Male,10.0,20.0,0.0,0.0,Basic,Annual,678.97,18.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
352660,46.0,Female,2.0,9.0,5.0,26.0,Premium,Annual,747.00,8.0,1.0
352661,22.0,Female,7.0,5.0,6.0,1.0,Basic,Quarterly,833.00,5.0,1.0
352662,47.0,Male,43.0,14.0,1.0,7.0,Basic,Annual,754.05,9.0,0.0
352663,34.0,Female,2.0,9.0,3.0,30.0,Basic,Quarterly,167.00,28.0,1.0
352664,52.0,Male,11.0,27.0,5.0,12.0,Premium,Monthly,711.00,25.0,1.0

In [4]:
# Seperate Features and Label
x_train = df.drop("Churn", axis=1)
y_train = df["Churn"]

In [5]:
x_train # Features

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction
0,42.0,Male,46.0,30.0,3.0,4.0,Standard,Annual,945.08,8.0
1,33.0,Female,43.0,17.0,1.0,15.0,Standard,Annual,987.79,12.0
2,26.0,Female,13.0,30.0,4.0,12.0,Premium,Quarterly,800.00,5.0
3,29.0,Female,9.0,23.0,10.0,24.0,Basic,Quarterly,119.00,19.0
4,38.0,Male,10.0,20.0,0.0,0.0,Basic,Annual,678.97,18.0
...,...,...,...,...,...,...,...,...,...,...
352660,46.0,Female,2.0,9.0,5.0,26.0,Premium,Annual,747.00,8.0
352661,22.0,Female,7.0,5.0,6.0,1.0,Basic,Quarterly,833.00,5.0
352662,47.0,Male,43.0,14.0,1.0,7.0,Basic,Annual,754.05,9.0
352663,34.0,Female,2.0,9.0,3.0,30.0,Basic,Quarterly,167.00,28.0
352664,52.0,Male,11.0,27.0,5.0,12.0,Premium,Monthly,711.00,25.0

In [6]:
y_train # Label

0         0.0
1         0.0
2         1.0
3         1.0
4         0.0
         ...
352660    1.0
352661    1.0
352662    0.0
352663    1.0
352664    1.0
Name: Churn, Length: 352665, dtype: float64

In [7]:
# Seperate Numerical and Categorical column names in the form of python list.
num_attribs = ["Age", "Tenure", "Usage Frequency", "Support Calls", "Payment Delay", "Total Spend", "Last Interaction"]
cat_attribs = ["Gender", "Subscription Type", "Contract Length"]

In [8]:
num_attribs

['Age',
 'Tenure',
 'Usage Frequency',
 'Support Calls',
 'Payment Delay',
 'Total Spend',
 'Last Interaction']

In [9]:
cat_attribs

['Gender', 'Subscription Type', 'Contract Length']

In [15]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [16]:
# Numerical Pipeline
num_pipeline = Pipeline([
    ("scaler", StandardScaler())
])

In [17]:
# Categorical Pipeline
cat_pipeline = Pipeline([
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

In [19]:
# Full Pipeline
full_pipeline = ColumnTransformer([
    ("num", num_pipeline, num_attribs),
    ("cat", cat_pipeline, cat_attribs)
])

In [20]:
# Fit and Transform the data
customer_churn_prepared = full_pipeline.fit_transform(x_train)

In [21]:
customer_churn_prepared

array([[ 0.21037671,  0.85527121,  1.65123805, ...,  1.        ,
         0.        ,  0.        ],
       [-0.51278391,  0.68145459,  0.13705613, ...,  1.        ,
         0.        ,  0.        ],
       [-1.07524218, -1.05671167,  1.65123805, ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [ 0.61213262,  0.68145459, -0.21237047, ...,  1.        ,
         0.        ,  0.        ],
       [-0.43243273, -1.6940393 , -0.79474813, ...,  0.        ,
         0.        ,  1.        ],
       [ 1.01388852, -1.17258942,  1.30181145, ...,  0.        ,
         1.        ,  0.        ]])

In [24]:
# Converting it back to pandas Dataframe
feature_names = full_pipeline.get_feature_names_out()

preprocessed = pd.DataFrame(
    customer_churn_prepared,
    columns=feature_names,
    index=x_train.index
)

In [25]:
preprocessed

,num__Age,num__Tenure,num__Usage Frequency,num__Support Calls,num__Payment Delay,num__Total Spend,num__Last Interaction,cat__Gender_Female,cat__Gender_Male,cat__Subscription Type_Basic,cat__Subscription Type_Premium,cat__Subscription Type_Standard,cat__Contract Length_Annual,cat__Contract Length_Monthly,cat__Contract Length_Quarterly
0,0.210377,0.855271,1.651238,-0.197156,-1.085320,1.300956,-0.753449,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
1,-0.512784,0.681455,0.137056,-0.848223,0.246158,1.478368,-0.288211,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
2,-1.075242,-1.056712,1.651238,0.128377,-0.116972,0.698312,-1.102379,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,-0.834189,-1.288467,0.835909,2.081578,1.335549,-2.130477,0.525957,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,-0.111028,-1.230528,0.486483,-1.173756,-1.569494,0.195568,0.409648,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352660,0.531781,-1.694039,-0.794748,0.453911,1.577636,0.478156,-0.753449,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
352661,-1.396647,-1.404345,-1.260650,0.779444,-1.448450,0.835389,-1.102379,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
352662,0.612133,0.681455,-0.212370,-0.848223,-0.722190,0.507441,-0.637140,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
352663,-0.432433,-1.694039,-0.794748,-0.197156,2.061810,-1.931091,1.572745,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
352664,1.013889,-1.172589,1.301811,0.453911,-0.116972,0.328617,1.223816,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0

In [26]:
# Saving Preprocessed data into a new csv file.
preprocessed.to_csv("training_data_preprocessed.csv", index=False)
print("Data saved Successfully!")

Data saved Successfully!

In [27]:
# Now load the testing dataset 
df = pd.read_csv("testing_data.csv")

In [28]:
df

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,62.0,Female,49.0,20.0,0.0,19.0,Basic,Monthly,175.00,22.0,1.0
1,29.0,Male,32.0,27.0,2.0,2.0,Standard,Quarterly,733.00,25.0,0.0
2,40.0,Female,39.0,16.0,8.0,0.0,Basic,Quarterly,542.00,3.0,1.0
3,23.0,Female,13.0,28.0,0.0,11.0,Basic,Quarterly,951.67,1.0,0.0
4,18.0,Male,10.0,15.0,3.0,15.0,Standard,Quarterly,970.00,17.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
88162,42.0,Female,5.0,27.0,3.0,3.0,Premium,Monthly,859.00,30.0,1.0
88163,34.0,Male,40.0,20.0,0.0,18.0,Basic,Annual,976.91,14.0,0.0
88164,26.0,Male,14.0,22.0,0.0,12.0,Standard,Annual,807.56,12.0,0.0
88165,43.0,Male,4.0,12.0,3.0,12.0,Standard,Annual,655.50,23.0,0.0
88166,29.0,Female,23.0,13.0,2.0,13.0,Premium,Quarterly,851.07,1.0,0.0

In [29]:
# Seperate Features and Label
x_test = df.drop("Churn", axis=1)
y_test = df["Churn"]

In [30]:
x_test

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction
0,62.0,Female,49.0,20.0,0.0,19.0,Basic,Monthly,175.00,22.0
1,29.0,Male,32.0,27.0,2.0,2.0,Standard,Quarterly,733.00,25.0
2,40.0,Female,39.0,16.0,8.0,0.0,Basic,Quarterly,542.00,3.0
3,23.0,Female,13.0,28.0,0.0,11.0,Basic,Quarterly,951.67,1.0
4,18.0,Male,10.0,15.0,3.0,15.0,Standard,Quarterly,970.00,17.0
...,...,...,...,...,...,...,...,...,...,...
88162,42.0,Female,5.0,27.0,3.0,3.0,Premium,Monthly,859.00,30.0
88163,34.0,Male,40.0,20.0,0.0,18.0,Basic,Annual,976.91,14.0
88164,26.0,Male,14.0,22.0,0.0,12.0,Standard,Annual,807.56,12.0
88165,43.0,Male,4.0,12.0,3.0,12.0,Standard,Annual,655.50,23.0
88166,29.0,Female,23.0,13.0,2.0,13.0,Premium,Quarterly,851.07,1.0

In [31]:
y_test

0        1.0
1        0.0
2        1.0
3        0.0
4        1.0
        ...
88162    1.0
88163    0.0
88164    0.0
88165    0.0
88166    0.0
Name: Churn, Length: 88167, dtype: float64

In [32]:
# Seperate Numerical and Categorical column names in the form of python list.
num_attribs = ["Age", "Tenure", "Usage Frequency", "Support Calls", "Payment Delay", "Total Spend", "Last Interaction"]
cat_attribs = ["Gender", "Subscription Type", "Contract Length"]

In [33]:
num_attribs

['Age',
 'Tenure',
 'Usage Frequency',
 'Support Calls',
 'Payment Delay',
 'Total Spend',
 'Last Interaction']

In [34]:
cat_attribs

['Gender', 'Subscription Type', 'Contract Length']

In [37]:
# Just transform the test data. Do NOT fit!
customer_churn_prepared_2 = full_pipeline.transform(x_test)

In [38]:
customer_churn_prepared_2

array([[ 1.81740032,  1.02908784,  0.48648273, ...,  0.        ,
         1.        ,  0.        ],
       [-0.83418863,  0.04412696,  1.30181145, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.04967435,  0.44969909,  0.0205806 , ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [-1.07524218, -0.9987728 ,  0.71943379, ...,  1.        ,
         0.        ,  0.        ],
       [ 0.29072789, -1.57816155, -0.44532153, ...,  1.        ,
         0.        ,  0.        ],
       [-0.83418863, -0.47732292, -0.328846  , ...,  0.        ,
         0.        ,  1.        ]])

In [41]:
# Converting it back to pandas Dataframe
feature_names = full_pipeline.get_feature_names_out()

preprocessed_2 = pd.DataFrame(
    customer_churn_prepared_2,
    columns=feature_names,
    index=x_test.index
)

In [42]:
preprocessed_2

,num__Age,num__Tenure,num__Usage Frequency,num__Support Calls,num__Payment Delay,num__Total Spend,num__Last Interaction,cat__Gender_Female,cat__Gender_Male,cat__Subscription Type_Basic,cat__Subscription Type_Premium,cat__Subscription Type_Standard,cat__Contract Length_Annual,cat__Contract Length_Monthly,cat__Contract Length_Quarterly
0,1.817400,1.029088,0.486483,-1.173756,0.730332,-1.897860,0.874887,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,-0.834189,0.044127,1.301811,-0.522689,-1.327407,0.420002,1.223816,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
2,0.049674,0.449699,0.020581,1.430511,-1.569494,-0.373388,-1.334998,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,-1.316296,-1.056712,1.418287,-1.173756,-0.238016,1.328330,-1.567617,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,-1.718052,-1.230528,-0.095895,-0.197156,0.246158,1.404470,0.293338,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88162,0.210377,-1.520223,1.301811,-0.197156,-1.206363,0.943390,1.805364,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
88163,-0.432433,0.507638,0.486483,-1.173756,0.609288,1.433173,-0.055591,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
88164,-1.075242,-0.998773,0.719434,-1.173756,-0.116972,0.729715,-0.288211,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
88165,0.290728,-1.578162,-0.445322,-0.197156,-0.116972,0.098077,0.991196,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
88166,-0.834189,-0.477323,-0.328846,-0.522689,0.004071,0.910450,-1.567617,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [43]:
# Saving Preprocessed data into a new csv file.
preprocessed_2.to_csv("testing_data_preprocessed.csv", index=False)
print("Data saved Successfully!")

Data saved Successfully!